-- auto-generated definition
create table dtsummary_organization_service_use
(
    dtsummary_organization_id                                       bigint       not null comment 'Identificador unico de la tabla'
        primary key,
    dtsummary_organization_version                                  int          null comment 'columna relleno de pentaho',
    dtsummary_organization_date_from                                datetime     null comment 'columna relleno de pentaho',
    dtsummary_organization_date_to                                  datetime     null comment 'columna relleno de pentaho',
    dtsummary_organization_organization_id                          varchar(255) null comment 'Identificador unico de la institucion obenido del sismtema CMI',
    institucion_institution                                         varchar(255) null comment 'Alias de la institucion',
    dtsummary_organization_paquete_id                               int          null comment 'Inetificador unico del paquete',
    dtsummary_organization_paquete_nombre                           varchar(255) null comment 'Nombre del paquete',
    dtsummary_anio                                                  int          null comment 'Año de obtencion de los datos',
    dtsummary_mes                                                   int          null comment 'Mes de obtencion de los datos',
    dtsummary_dia                                                   int          null comment 'Dia de obtencion de los datos',
    `Red Avanzada (Mbps)`                                           bigint       null,
    `Asignación de bloques IPv6`                                    bigint       null,
    `LAN Extendida`                                                 bigint       null,
    `Túneles de Datos`                                              bigint       null,
    Eduroam                                                         bigint       null,
    `Firewall Perimetral (NGFW)`                                    bigint       null,
    `Firewall para sitios Web (WAF)`                                bigint       null,
    `Protección de Denegación de Servicio (Anti-DDoS)`              bigint       null,
    AntiSpam                                                        bigint       null,
    `DNS Seguro`                                                    bigint       null,
    Honeypots                                                       bigint       null,
    `Alertas de Seguridad (YARI)`                                   bigint       null,
    `Equipo de Respuesta a Incidentes de Seguridad (CSIRT)`         bigint       null,
    `Security Center`                                               bigint       null,
    Federaciones                                                    bigint       null,
    `Research Cloud`                                                bigint       null,
    `Institucional Cloud`                                           bigint       null,
    `Backup como Servicio`                                          bigint       null,
    `Backup Ejecutivo`                                              bigint       null,
    Supercomputador                                                 bigint       null,
    `Cuadro de Mando Integral (CMI)`                                bigint       null,
    Helpdesk                                                        bigint       null,
    `Monitoreo de enlaces e infraestructura`                        bigint       null,
    `Video conferencia multipunto`                                  bigint       null,
    `Grabación eventos y transmisión en vivo`                       bigint       null,
    `Audio Streaming (Radio Online)`                                bigint       null,
    `Plataforma LMS ELSA (Estudiantes Matriculados / Concurrentes)` bigint       null,
    `Plataforma MOOC`                                               bigint       null,
    `Portal de Acceso a Servicios CEDIA`                            bigint       null,
    `Filesender (1Tb)`                                              bigint       null,
    `VENUE (Salón de conferencias virtual)`                         bigint       null,
    `Mirror de software open source`                                bigint       null,
    `Repositorio Nacional de OA (ROA)`                              bigint       null,
    `Acceso a Global Knowledge Academics`                           bigint       null,
    `Red de Repositorios de Acceso Abierto del Ecuador (RRAAE)`     bigint       null,
    `Repositorio Semántico de investigadores (REDI)`                bigint       null,
    `Red de Recursos Tecnológicos de Ecuador RETEC`                 bigint       null,
    `FONDO AVANTE`                                                  bigint       null,
    `FONDO DIVULGA`                                                 bigint       null,
    `FONDO PONENTE`                                                 bigint       null,
    `FONDO I+D+i`                                                   bigint       null,
    `FONDO 1 A 1`                                                   bigint       null,
    `FONDO REGISTRA`                                                bigint       null,
    `FONDO ACELERA`                                                 bigint       null,
    `REDES DE IMPACTO`                                              bigint       null,
    `PLAN DE MEJORA I+D+i`                                          bigint       null,
    `MENTORIA I+D+i`                                                bigint       null,
    `BOLETINES DE VIGILANCIA TECNOLÓGICA`                           bigint       null,
    `Capacitación EFC`                                              bigint       null,
    `Certificación EFC`                                             bigint       null,
    `EVENTOS DE INNOVACIÓN ABIERTA`                                 bigint       null,
    `REVISTA CONNECT`                                               bigint       null,
    `ALERTA DE FONDOS Y SOCIOS`                                     bigint       null,
    `USO DE SALAS EN QUITO - CUENCA`                                bigint       null,
    `Repositorio del Conocimiento`                                  bigint       null,
    UDECIDE                                                         bigint       null,
    `Diagnostico CTI`                                               bigint       null,
    `AMBIENTAL, SOCIAL Y DE GOBERNANZA`                             bigint       null,
    `Medición de Huella de Carbono`                                 bigint       null,
    `Acompañamiento Técnico en Fondos Europeos`                     bigint       null,
    `Vigilancia Técnologica e Inteligencia Competitiva`             bigint       null,
    `Evaluación de Proyectos`                                       bigint       null,
    `Evaluación PI`                                                 bigint       null,
    `Protección PI`                                                 bigint       null,
    `Vigilancia y mantenimiento PI`                                 bigint       null,
    `Valoración de activos de conocimiento`                         bigint       null,
    `Divulgación de Activos de conocimiento`                        bigint       null,
    `Comercialización de Activos de conocimiento`                   bigint       null,
    `Evaluación de Obras por Pares`                                 bigint       null,
    `Edición de Obras`                                              bigint       null,
    `Diagramación de Obras`                                         bigint       null,
    `Traducción de Obras`                                           bigint       null,
    `Fabricación e Impresión Digital (Digitals)`                    bigint       null,
    `Encuentro de Autoridades Directivas`                           bigint       null,
    `CIO University`                                                bigint       null,
    `Participación TIC.EC`                                          bigint       null,
    `Semana de la Propiedad Intelectual`                            bigint       null,
    `Feria Nacional de Invenciones Académicas`                      bigint       null,
    `Trend Labs`                                                    bigint       null,
    `Concursos Innova CEDIA`                                        bigint       null,
    `Viajes Inmersivos`                                             bigint       null,
    `Material de estudio y consulta`                                bigint       null,
    `Difución de Convocatorias Fondo Horizonte Europa`              bigint       null,
    `Infodays CEDIA`                                                bigint       null,
    `Semana de la Innovación`                                       bigint       null,
    `Foro de Rectores`                                              bigint       null,
    `Servicio de SOC: SIEM - Protección Privada`                    int          null,
    `EAGORA Science by GKA`                                         int          null,
    `COMPETENCIAS DIGITALES DE LOS DOCENTES`                        int          null,
    `CAPACIDADES I+D+I DE LOS INVESTIGADORES`                       int          null,
    `CAPACIDADES DE INNOVACION DE LA INSTITUCION`                   int          null,
    `NIVEL DE MADUREZ EN TRANSFORMACION DIGITAL DE LA INSTITUCION`  int          null,
    `PLAN DE MEJORA CTI`                                            int          null
);

create index idx_dtsummary_organization_service_use_lookup
    on dtsummary_organization_service_use (dtsummary_organization_organization_id, institucion_institution,
                                           dtsummary_organization_paquete_id, dtsummary_organization_paquete_nombre,
                                           dtsummary_anio, dtsummary_mes, dtsummary_dia);

create index idx_dtsummary_organization_service_use_tk
    on dtsummary_organization_service_use (dtsummary_organization_id);